version: '3'

services:
  web:
    build: ./client
    ports:
     - "8080:8080"

  backend:
    build: ./server
    ports:
     - "3000:3000"
    links:
      - database

  database:
    image: mongo
    ports:
      - 27017:27017

    